---
title: "CoronaMapping"
author: "G.Robertson"
date: "01/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Mapping current coronavirus information from Worldometers

Packages needed
```{r}
library(tidyverse)
library(rvest)
library(rgdal)
library(RColorBrewer)
```

Webscrape the data
```{r}
url <- "https://www.worldometers.info/coronavirus/"
all <-url%>%read_html()%>%html_table()%>%.[[1]]
```

Tidy it up
```{r}
# exclude the continents and world variables
coronavirus <- all[9:230,-1]

# Remove symbols from formatting of numbers
coronavirus[]<-lapply(coronavirus, function(x) (gsub("\\,|\\+", "", (x))))

# convert all but the first and last column to numeric
coronavirus[,c(2:14, 16:21)] <- sapply(coronavirus[c(2:14, 16:21)],as.numeric)

# rename the cols
colnames(coronavirus) <- c("Country", "TotalCases", "NewCases", "TotalDeaths",       
                           "NewDeaths", "TotalRecovered", "NewRecovered", "ActiveCases",       
                           "CriticalCases", "Cases_Per1M", "Deaths_per1M", "TotalTests",         
                           "Tests_per1M", "Population", "Continent", "1CaseeveryXppl", 
                           "1DeatheveryXppl",  "1TesteveryXppl",   "NewCases_per1M",
                           "NewDeaths_per1M", "ActiveCases_per1M")
```

Load a map file and tweak the formatting
```{r}
map_object <- readOGR("C:/Users/georg/Documents/R_Maps/TM_WORLD_BORDERS_SIMPL-0.3.shp")
     
euro_map <- map_object[map_object@data$REGION==150, ]

plot(euro_map, xlim=c(30,50) , ylim=c(35, 75))
```

